In [1]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving results.csv to results (1).csv

In [5]:
df = pd.read_csv("results.csv")
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [7]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49287 entries, 0 to 49286
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49287 non-null  object
 1   home_team   49287 non-null  object
 2   away_team   49287 non-null  object
 3   home_score  49215 non-null  float64
 4   away_score  49215 non-null  float64
 5   tournament  49287 non-null  object
 6   city        49287 non-null  object
 7   country     49287 non-null  object
 8   neutral     49287 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [9]:
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')

In [10]:
def get_result (row):
  if row['home_score'] > row['away_score']:
    return "Home Win"
  elif row['home_score'] < row['away_score']:
    return "Away Win"
  else:
    return "Draw"

df['result'] = df.apply(get_result, axis=1)

In [11]:
df['goal_diff'] = df['home_score'] - df['away_score']

In [12]:
df[['home_team', 'away_team', 'home_score', 'away_score', 'result']].head(10)

  home_team away_team  home_score  away_score    result
0  Scotland   England         0.0         0.0      Draw
1   England  Scotland         4.0         2.0  Home Win
2  Scotland   England         2.0         1.0  Home Win
3   England  Scotland         2.0         2.0      Draw
4  Scotland   England         3.0         0.0  Home Win
5  Scotland     Wales         4.0         0.0  Home Win
6   England  Scotland         1.0         3.0  Away Win
7     Wales  Scotland         0.0         2.0  Away Win
8  Scotland   England         7.0         2.0  Home Win
9  Scotland     Wales         9.0         0.0  Home Win

In [13]:
df.to_csv("cleaned_results.csv", index=False)

In [14]:
files.download("cleaned_results.csv")